# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

ENV["RUBY_ENV"] = 'test'

Dir[File.expand_path("../../app", __FILE__) + '/**/*.rb'].each{ |f| require f }
require 'yaml'
require 'mysql2'

database = YAML::load(File.open(File.expand_path("../../config/database.yml", __FILE__)))
$client = Mysql2::Client.new(database[ENV["RUBY_ENV"]])

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
